{
 "title": "Opentelemetry Application APM",
 "tags": [
  "application",
  "APM",
  "otel"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": { "query": "label_values(app)" } },
   { "name": "search", "label": "search log", "query": "get" }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Memory Usage(measure of memory used)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (process_runtime_jvm_memory_usage{app=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executing threads",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (process_runtime_jvm_threads_count{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "http duration bucket",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, http_status_code) (rate(http_server_duration_bucket{app=~\"$app\"}[1m])))"
    }
   ]
  },
  {
   "title": "DB connection",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(db_client_connections_usage{state=\"used\"})",
     "legendFormat": "used"
    },
    {
     "expr": "max(db_client_connections_usage{state=\"idle\"})",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Threads(number of executing threads)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(instance) (process_runtime_jvm_threads_count{app=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_active_requests" }
   ]
  },
  {
   "title": "Classes(number ofclasses loaded since JVM start)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(instance) (process_runtime_jvm_classes_loaded_total{app=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow chart",
   "type": "nodeGraph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 19 },
   "targets": [
    {
     "limit": 20,
     "query": "a22ad1c2286bc72e345ea9d29305bc55",
     "serviceMapQuery": "{client=\"spring-client\"}",
     "serviceName": "spring-client"
    }
   ]
  },
  {
   "title": "Log Analysis & Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log per app",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "{app=~\"$app\"} |= `$search`"
      }
     ]
    }
   ]
  }
 ]
}